### ISSUE TITLE
Remove stale pipeline instances

### ISSUE THREAD

**Issue by aviweit** [5GZORRO/datalake#10]
Overtime, the number of pipeline instances such as ingest ones, increases. There should be a mechanism to remove such stale instances to free the overall resource consumption from k8s db (etcd).

Perhaps there could be some configuration parameter, per every user, that defines the number of instances to preserve with some default value. Instances above that will be remove.

The config may be passed during user registration.
A background thread can run every t time and delete oldest instances according to the per-user configuration.

**Comment by KalmanMeth** [comment]
handled by PR #44
